env: "local"

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "1111"
  dbname: "urls"
  sslmode: "disable"

http_server:
  address: "0.0.0.0:8080"
  timeout: 10s
  idle_timeout: 60s
